from pydantic import BaseModel

# This file contains data models for various requests and responses in the CodeAtlas API.

# Represents a request to ingest code from a repository.
class IngestRequest(BaseModel):
    repo_root: str  # The root directory of the repository to be ingested.


# Represents a resolved target, which could be a specific part of the code or a module.
class ResolvedTarget(BaseModel):
    kind: str | None = None  # Type of the target (e.g., 'function', 'module').
    id: str | None = None  # Unique identifier for the target.


# Represents a turn in the conversation history, which includes a question and an answer.
class HistoryTurn(BaseModel):
    question: str  # The user's question or prompt.
    answer: str  # The response generated by the system.
    resolved_target: ResolvedTarget | None = None  # Target that was resolved during this turn.


# Represents a request to ask a question and provide context from previous interactions.
class AskRequest(BaseModel):
    question: str  # The user's question.
    history: list[HistoryTurn] = []  # List of past interactions.


# Represents a request to validate an improved version of code.
class ValidateFixRequest(BaseModel):
    repo_root: str  # The root directory of the repository containing the code.
    entity_id: str  # Unique identifier for the specific part of the code being fixed.
    improved_code: str  # The improved version of the code.


# Represents a request to apply an improvement to a piece of code.
class ApplyFixRequest(BaseModel):
    repo_root: str  # The root directory of the repository containing the code.
    entity_id: str  # Unique identifier for the specific part of the code being fixed.
    improved_code: str  # The improved version of the code.